
import SocialPreview from "./SocialPreview";

type ContentType = "video" | "post" | "carousel";

export default function ContentPreview({ loading, text, hashtags, imagePrompt, imageUrl, videoUrl, contentType }:{
  loading:boolean; text?:string; hashtags?:string[]; imagePrompt?:string; imageUrl?:string; videoUrl?:string; contentType:ContentType;
}){
  if(loading){
    return <div className="h-full flex flex-col items-center justify-center text-sm text-slate-500">
      <div className="w-10 h-10 border-4 border-vl_primary/40 border-t-vl_primary rounded-full animate-spin mb-3" />
      <p>AI is working…</p>
    </div>;
  }
  if(!text){
    return <div className="h-full flex items-center justify-center text-sm text-slate-400">Your content will appear here.</div>;
  }
  return (
    <div className="space-y-4">
      <div className="vl-card p-4">
        <h3 className="text-sm font-semibold text-slate-800 mb-2">Post text</h3>
        <p className="text-sm whitespace-pre-wrap text-slate-800">{text}</p>
      </div>

      <div className="grid md:grid-cols-2 gap-4">
        <div className="vl-card p-4">
          <h3 className="text-sm font-semibold text-slate-800 mb-2">Suggested image</h3>
          {imageUrl? (<>
            <img src={imageUrl} alt="Generated by AI" className="w-full rounded-xl border border-slate-200 mb-3" />
            <a href={imageUrl} download className="vl-btn vl-btn-ghost text-xs">⬇️ Download</a>
          </>):(<>
            <p className="text-xs text-slate-700 mb-2">{imagePrompt || "A visual idea is suggested based on the text."}</p>
            <p className="text-[11px] text-slate-400">Click “Generate image” to create the visual.</p>
          </>)}
        </div>
        <div className="vl-card p-4">
          <h3 className="text-sm font-semibold text-slate-800 mb-2">Hashtags</h3>
          <p className="text-xs text-slate-700">{hashtags?.length? hashtags.map(h=>`#${h}`).join("  ") : "#viralobby  #ai  #contentcreator  #digitalmarketing"}</p>
        </div>
      </div>

      <SocialPreview text={text} hashtags={hashtags} contentType={contentType} />

      {!!videoUrl && (
        <div className="vl-card p-4">
          <h3 className="text-sm font-semibold text-slate-800 mb-2">Generated video</h3>
          <video controls className="w-full rounded-xl border border-slate-200 mb-2" src={videoUrl} />
          <a href={videoUrl} download className="vl-btn vl-btn-ghost text-xs">⬇️ Download video</a>
        </div>
      )}
    </div>
  );
}
