
type Props = {
  loading: boolean;
  text?: string;
  hashtags?: string[];
  imagePrompt?: string;
  imageUrl?: string;
};

import { useLanguage } from "../context/LanguageContext";

const ContentPreview: React.FC<Props> = ({
  loading,
  text,
  hashtags,
  imagePrompt,
  imageUrl
}) => {
  const { lang } = useLanguage();

  if (loading) {
    return (
      <div className="h-full flex flex-col items-center justify-center text-sm text-slate-500">
        <div className="w-10 h-10 border-4 border-vlPurple/40 border-t-vlPurple rounded-full animate-spin mb-3" />
        <p>
          {lang === "fr"
            ? "L’IA travaille pour toi…"
            : lang === "ar"
            ? "الذكاء الاصطناعي يعمل من أجلك…"
            : "AI is working for you..."}
        </p>
      </div>
    );
  }

  if (!text) {
    return (
      <div className="h-full flex flex-col items-center justify-center text-sm text-slate-400 text-center px-4">
        <p>
          {lang === "fr"
            ? "Ton contenu apparaîtra ici après la génération. Décris ton idée à gauche et clique sur “Générer”."
            : lang === "ar"
            ? "سيظهر المحتوى هنا بعد التوليد. صف فكرتك في الجهة اليسرى واضغط على «توليد»."
            : "Your content will appear here after generation. Describe your idea on the left and click “Generate”."}
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-4 h-full flex flex-col">
      {/* Texte du post */}
      <div className="bg-white border border-slate-200 rounded-2xl p-4 shadow-sm">
        <h3 className="text-sm font-semibold text-slate-800 mb-2">
          {lang === "fr"
            ? "Texte du post"
            : lang === "ar"
            ? "نص المنشور"
            : "Post text"}
        </h3>
        <p className="text-sm whitespace-pre-wrap text-slate-800">{text}</p>
      </div>

      <div className="grid md:grid-cols-2 gap-4">
        {/* Image proposée */}
        <div className="bg-white border border-slate-200 rounded-2xl p-4 shadow-sm">
          <h3 className="text-sm font-semibold text-slate-800 mb-2">
            {lang === "fr"
              ? "Image proposée"
              : lang === "ar"
              ? "الصورة المقترحة"
              : "Suggested image"}
          </h3>

          {imageUrl ? (
            <>
              <img
                src={imageUrl}
                alt="Generated by AI"
                className="w-full rounded-xl border border-slate-200 mb-3"
              />
              <a
                href={imageUrl}
                download
                className="inline-flex items-center px-3 py-1.5 text-xs rounded-lg border border-slate-300 bg-slate-50 hover:bg-slate-100"
              >
                ⬇️{" "}
                {lang === "fr"
                  ? "Télécharger l’image"
                  : lang === "ar"
                  ? "تنزيل الصورة"
                  : "Download image"}
              </a>
            </>
          ) : (
            <>
              <p className="text-xs text-slate-700 mb-2">
                {imagePrompt ||
                  (lang === "fr"
                    ? "Une idée de visuel est proposée en fonction du texte. Tu peux générer l’image avec l’IA."
                    : lang === "ar"
                    ? "تم اقتراح فكرة للصورة بناءً على النص. يمكنك توليد الصورة بالذكاء الاصطناعي."
                    : "A visual idea is suggested based on the text. You can generate the image with AI.")}
              </p>
              <p className="text-[11px] text-slate-400">
                {lang === "fr"
                  ? "Clique sur “Générer l’image avec l’IA” pour créer le visuel."
                  : lang === "ar"
                  ? "اضغط على «توليد صورة بالذكاء الاصطناعي» لإنشاء الصورة."
                  : "Click “Generate image with AI” to create the visual."}
              </p>
            </>
          )}
        </div>

        {/* Hashtags */}
        <div className="bg-white border border-slate-200 rounded-2xl p-4 shadow-sm">
          <h3 className="text-sm font-semibold text-slate-800 mb-2">
            Hashtags
          </h3>
          <p className="text-xs text-slate-700">
            {hashtags && hashtags.length
              ? hashtags.map((h) => `#${h}`).join("  ")
              : "#viralobby  #ai  #contentcreator  #digitalmarketing  #morocco"}
          </p>
          <p className="text-[11px] text-slate-400 mt-1">
            {lang === "fr"
              ? "Tu peux copier ces hashtags et les coller directement dans ta légende."
              : lang === "ar"
              ? "يمكنك نسخ هذه الوسوم ولصقها مباشرة في المنشور."
              : "You can copy these hashtags and paste them directly into your caption."}
          </p>
        </div>
      </div>
    </div>
  );
};

export default ContentPreview;
