
import Sidebar from "@/components/Sidebar";
import Topbar from "@/components/Topbar";

export default function ReviewPage() {
  return (
    <div className="app-shell">
      <Sidebar />
      <div className="main-area">
        <Topbar
          title="Review"
          subtitle="Polish AI drafts before publishing."
          right={null}
        />
        <div className="page-body p-6 grid grid-cols-1 lg:grid-cols-[minmax(0,2.3fr)_minmax(0,1fr)] gap-6">
          <section className="card-light p-5 space-y-3">
            <header className="flex items-center justify-between">
              <div>
                <h2 className="text-sm font-semibold text-slate-50">
                  Facebook Ad – Amaly Kids Club Launch
                </h2>
                <p className="text-xs text-slate-500 mt-0.5">
                  Draft generated by Viralobby AI · 2 hours ago
                </p>
              </div>
              <div className="flex items-center gap-2 text-xs text-slate-400">
                <button className="btn-ghost text-xs px-2 py-1">↩ Undo</button>
                <button className="btn-ghost text-xs px-2 py-1">↪ Redo</button>
                <button className="btn-ghost text-xs px-2 py-1">⟳ History</button>
              </div>
            </header>

            <article className="mt-3 space-y-3 text-sm text-slate-200">
              <h3 className="text-base font-semibold">
                🎓 Give your child a head start with Amaly Kids Club
              </h3>
              <p>
                Looking for a space where your child can learn, create and collaborate?
                Amaly Kids Club in Casablanca helps students from K2 to Grade 9 discover
                global citizenship, digital skills and creativity through playful projects.
              </p>
              <p>
                With SDG-based activities, storytelling workshops, coding, and hands-on
                challenges, your child learns how to think, solve problems and work in teams.
                Places are limited – reserve a spot today and join a new generation of learners.
              </p>
              <p className="font-medium text-slate-100">
                #AmalyKidsClub #Education #Casablanca #FutureReady
              </p>
            </article>
          </section>

          <aside className="space-y-4">
            <div className="card-light p-4 space-y-2">
              <h3 className="text-[11px] font-semibold uppercase tracking-wide text-slate-500">
                Quick actions
              </h3>
              <div className="space-y-2 text-xs">
                <button className="btn-ghost w-full justify-between">
                  <span>Refine tone</span> <span>↻</span>
                </button>
                <button className="btn-ghost w-full justify-between">
                  <span>Translate</span> <span>🌍</span>
                </button>
                <button className="btn-ghost w-full justify-between">
                  <span>Shorten</span> <span>⇣</span>
                </button>
                <button className="btn-ghost w-full justify-between">
                  <span>Improve hook</span> <span>✨</span>
                </button>
              </div>
            </div>

            <div className="card-light p-4 space-y-3">
              <h3 className="text-[11px] font-semibold uppercase tracking-wide text-slate-500">
                Performance preview
              </h3>
              <div className="flex items-center gap-4">
                <div className="h-16 w-16 rounded-full border-4 border-vl_accent grid place-items-center text-sm font-semibold text-vl_accent">
                  86
                </div>
                <div className="text-xs text-slate-400">
                  <p className="font-semibold text-vl_accent">High potential</p>
                  <p>
                    Hook strength, clarity and CTA look strong.
                    This ad is likely to perform well with the right audience targeting.
                  </p>
                </div>
              </div>
            </div>

            <div className="card-light p-4 space-y-2">
              <button className="btn-ghost w-full justify-center text-xs">
                Save as draft
              </button>
              <button className="btn-primary w-full justify-center text-xs">
                Publish to Meta Suite →
              </button>
            </div>
          </aside>
        </div>
      </div>
    </div>
  );
}
